[package]
name = "th-ecdsa"
version = "0.1.0"

[lib]
name = "multi_party_ecdsa"
crate-type = ["dylib"]

[dependencies]
rust-gmp = "0.5.0"
rand = "0.4"
hex = "0.3.2"

[dependencies.secp256k1]
version = "0.9.0"
features = ["rand"]
