[package]
name = "th-ecdsa"
version = "0.1.0"

[lib]
crate-type = ["dylib"]

[dependencies]
cryptography-utils = { git = "https://github.com/KZen-networks/cryptography-utils" }
paillier = { path = "../../rust_paillier/rust-paillier" }
#paillier = { git = "https://github.com/mortendahl/rust-paillier", branch = "dev" }
